import 'package:flutter/material.dart';
import 'package:bus_tracking_app/models/route.dart' as app_route;
import 'package:bus_tracking_app/core/services/route_service.dart';

class AddEditRouteScreen extends StatefulWidget {
  final app_route.Route? route; // null if adding new route

  const AddEditRouteScreen({super.key, this.route});

  @override
  State<AddEditRouteScreen> createState() => _AddEditRouteScreenState();
}

class _AddEditRouteScreenState extends State<AddEditRouteScreen> {
  late final RouteService _routeService;
  late final TextEditingController _routeNumberController;
  late final TextEditingController _nameController;
  late final TextEditingController _startLocationController;
  late final TextEditingController _endLocationController;
  late final TextEditingController _distanceController;
  late final TextEditingController _durationController;

  bool _isLoading = false;
  bool _isActive = true;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    _routeService = RouteService();

    // Initialize controllers with existing data if editing
    _routeNumberController = TextEditingController(
      text: widget.route?.routeNumber ?? '',
    );
    _nameController = TextEditingController(
      text: widget.route?.name ?? '',
    );
    _startLocationController = TextEditingController(
      text: widget.route?.startLocation ?? '',
    );
    _endLocationController = TextEditingController(
      text: widget.route?.endLocation ?? '',
    );
    _distanceController = TextEditingController(
      text: widget.route?.distance.toString() ?? '',
    );
    _durationController = TextEditingController(
      text: widget.route?.estimatedDuration.toString() ?? '',
    );

    _isActive = widget.route?.isActive ?? true;
  }

  @override
  void dispose() {
    _routeNumberController.dispose();
    _nameController.dispose();
    _startLocationController.dispose();
    _endLocationController.dispose();
    _distanceController.dispose();
    _durationController.dispose();
    super.dispose();
  }

  bool _validateInputs() {
    if (_routeNumberController.text.isEmpty) {
      setState(() => _errorMessage = 'Route number is required');
      return false;
    }
    if (_nameController.text.isEmpty) {
      setState(() => _errorMessage = 'Route name is required');
      return false;
    }
    if (_startLocationController.text.isEmpty) {
      setState(() => _errorMessage = 'Start location is required');
      return false;
    }
    if (_endLocationController.text.isEmpty) {
      setState(() => _errorMessage = 'End location is required');
      return false;
    }
    if (_distanceController.text.isEmpty) {
      setState(() => _errorMessage = 'Distance is required');
      return false;
    }
    if (_durationController.text.isEmpty) {
      setState(() => _errorMessage = 'Estimated duration is required');
      return false;
    }

    // Validate numeric values
    if (double.tryParse(_distanceController.text) == null) {
      setState(() => _errorMessage = 'Distance must be a valid number');
      return false;
    }
    if (int.tryParse(_durationController.text) == null) {
      setState(() => _errorMessage = 'Duration must be a valid integer');
      return false;
    }

    setState(() => _errorMessage = null);
    return true;
  }

  Future<void> _saveRoute() async {
    if (!_validateInputs()) return;

    setState(() => _isLoading = true);

    try {
      final distance = double.parse(_distanceController.text);
      final duration = int.parse(_durationController.text);

      if (widget.route == null) {
        // Create new route
        final newRoute = app_route.Route(
          id: '', // Will be generated by Firebase
          routeNumber: _routeNumberController.text.trim(),
          name: _nameController.text.trim(),
          startLocation: _startLocationController.text.trim(),
          endLocation: _endLocationController.text.trim(),
          distance: distance,
          estimatedDuration: duration,
          isActive: _isActive,
          stopIds: [],
        );

        final routeId = await _routeService.createRoute(newRoute);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Route ${newRoute.routeNumber} created successfully!'),
              backgroundColor: Colors.green,
              duration: const Duration(seconds: 2),
            ),
          );
          Navigator.of(context).pop(true); // Return true to refresh list
        }
      } else {
        // Update existing route
        final updatedRoute = widget.route!.copyWith(
          routeNumber: _routeNumberController.text.trim(),
          name: _nameController.text.trim(),
          startLocation: _startLocationController.text.trim(),
          endLocation: _endLocationController.text.trim(),
          distance: distance,
          estimatedDuration: duration,
          isActive: _isActive,
        );

        await _routeService.updateRouteObject(
          widget.route!.id,
          updatedRoute,
        );

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Route ${updatedRoute.routeNumber} updated successfully!'),
              backgroundColor: Colors.green,
              duration: const Duration(seconds: 2),
            ),
          );
          Navigator.of(context).pop(true); // Return true to refresh list
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() => _errorMessage = 'Error saving route: $e');
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error: ${_errorMessage}'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.route != null;
    final title = isEditing ? 'Edit Route' : 'Add New Route';

    return Scaffold(
      appBar: AppBar(
        elevation: 0,
        backgroundColor: Colors.red.shade700,
        title: Text(
          title,
          style: const TextStyle(fontWeight: FontWeight.bold, color: Colors.white),
        ),
      ),
      body: SingleChildScrollView(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Error Message
              if (_errorMessage != null)
                Container(
                  padding: const EdgeInsets.all(12),
                  margin: const EdgeInsets.only(bottom: 16),
                  decoration: BoxDecoration(
                    color: Colors.red.shade100,
                    border: Border.all(color: Colors.red),
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(
                    _errorMessage!,
                    style: TextStyle(color: Colors.red.shade900),
                  ),
                ),

              // Route Number Field
              Text(
                'Route Number',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey.shade700,
                ),
              ),
              const SizedBox(height: 8),
              TextField(
                controller: _routeNumberController,
                decoration: InputDecoration(
                  hintText: 'e.g., 138',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  prefixIcon: const Icon(Icons.pin),
                ),
              ),
              const SizedBox(height: 24),

              // Route Name Field
              Text(
                'Route Name',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey.shade700,
                ),
              ),
              const SizedBox(height: 8),
              TextField(
                controller: _nameController,
                decoration: InputDecoration(
                  hintText: 'e.g., Colombo - Malabe Express',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  prefixIcon: const Icon(Icons.route),
                ),
              ),
              const SizedBox(height: 24),

              // Start Location Field
              Text(
                'Start Location',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey.shade700,
                ),
              ),
              const SizedBox(height: 8),
              TextField(
                controller: _startLocationController,
                decoration: InputDecoration(
                  hintText: 'e.g., Colombo Fort',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  prefixIcon: const Icon(Icons.location_on),
                ),
              ),
              const SizedBox(height: 24),

              // End Location Field
              Text(
                'End Location',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w600,
                  color: Colors.grey.shade700,
                ),
              ),
              const SizedBox(height: 8),
              TextField(
                controller: _endLocationController,
                decoration: InputDecoration(
                  hintText: 'e.g., Malabe',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  prefixIcon: const Icon(Icons.location_on),
                ),
              ),
              const SizedBox(height: 24),

              // Distance and Duration Row
              Row(
                children: [
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Distance (km)',
                          style: TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: Colors.grey.shade700,
                          ),
                        ),
                        const SizedBox(height: 8),
                        TextField(
                          controller: _distanceController,
                          keyboardType: const TextInputType.numberWithOptions(
                            decimal: true,
                          ),
                          decoration: InputDecoration(
                            hintText: 'e.g., 15.5',
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            prefixIcon: const Icon(Icons.straighten),
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Duration (min)',
                          style: TextStyle(
                            fontSize: 14,
                            fontWeight: FontWeight.w600,
                            color: Colors.grey.shade700,
                          ),
                        ),
                        const SizedBox(height: 8),
                        TextField(
                          controller: _durationController,
                          keyboardType: TextInputType.number,
                          decoration: InputDecoration(
                            hintText: 'e.g., 45',
                            border: OutlineInputBorder(
                              borderRadius: BorderRadius.circular(12),
                            ),
                            prefixIcon: const Icon(Icons.timer),
                          ),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              // Active Status Toggle
              if (isEditing)
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                  decoration: BoxDecoration(
                    border: Border.all(color: Colors.grey.shade300),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Text(
                        'Route Status',
                        style: TextStyle(
                          fontSize: 14,
                          fontWeight: FontWeight.w600,
                          color: Colors.grey.shade700,
                        ),
                      ),
                      Switch(
                        value: _isActive,
                        onChanged: (value) {
                          setState(() => _isActive = value);
                        },
                        activeColor: Colors.green,
                      ),
                    ],
                  ),
                ),
              if (isEditing) const SizedBox(height: 24),

              // Save Button
              SizedBox(
                width: double.infinity,
                height: 56,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _saveRoute,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.red.shade700,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          height: 24,
                          width: 24,
                          child: CircularProgressIndicator(
                            valueColor: AlwaysStoppedAnimation<Color>(
                              Colors.white,
                            ),
                          ),
                        )
                      : Text(
                          isEditing ? 'Update Route' : 'Create Route',
                          style: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                ),
              ),
              const SizedBox(height: 16),

              // Cancel Button
              SizedBox(
                width: double.infinity,
                height: 56,
                child: OutlinedButton(
                  onPressed: _isLoading ? null : () => Navigator.pop(context),
                  style: OutlinedButton.styleFrom(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text(
                    'Cancel',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
